### ISSUE TITLE
Comentarios a los formularios

### ISSUE THREAD

**Issue by aralvarez** [a1bandas/DAW2M#1]
En todos los formularios: faltan el nombre del autor y fecha.
Bastantes formularios no son válidos según el W3C.

Formulario 1:
  Todos los <input> deberían tener un atributo "name".
Formulario 3:
  Los dos elementos <textarea> deberían tener diferente nombre de variable.
Formulario 5:
  Los "Estudios" son "checkbox", no "radio".
  En los "radio" y "checkbox", el texto suele estar a la izquierda del texto, no a la derecha.
Formulario 7:
  Los controles "input" no tienen nombre de variable asociada.
Formulario 10:
  Falta el botón "restablecer".
  No se han dado los valores por defecto.  
  El control "textarea" no tiene nombre de variable asociada.

**Comment by a1bandas** [comment]
We are putting all our effort and motivation in solve these problems and other problems with the  user experience.
We appreciate your interest in our product.
Sincerly, Alejandro Carrillo. Development boss.
